IF OBJECT_ID('spSalvarUsuario') IS NOT NULL
	DROP PROCEDURE spSalvarUsuario
GO
CREATE PROCEDURE spSalvarUsuario (
	@NOME VARCHAR(100),
	@EMAIL VARCHAR(30),
	@SENHA VARCHAR(100),
	@TELEFONE VARCHAR(30) = NULL,
	@ENDERECO VARCHAR(100) = NULL
)
AS
	BEGIN

		INSERT INTO Usuario ( Nome, Email, Senha, Telefone, Endereco ) VALUES ( @NOME, @EMAIL, @SENHA, @TELEFONE, @ENDERECO )

		SELECT SCOPE_IDENTITY()

	END;