IF OBJECT_ID('Usuario') IS NOT NULL
	DROP TABLE Usuario
GO
CREATE TABLE Usuario (

	UsuarioId INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	Senha VARCHAR(100) NOT NULL,
	Telefone VARCHAR(20) NULL,
	Endereco VARCHAR(100) NULL,
	PasswordResetToken VARCHAR(255) NULL
);